export const TOPICS = {
  EVENT_LIFECYCLE: process.env.KAFKA_EVENT_LIFECYCLE_TOPIC || 'eventzen.event.lifecycle',
  REGISTRATION_LIFECYCLE: process.env.KAFKA_REGISTRATION_TOPIC || 'eventzen.registration.lifecycle',
  PAYMENT_LIFECYCLE: process.env.KAFKA_PAYMENT_TOPIC || 'eventzen.payment.lifecycle',
  DLQ: process.env.KAFKA_DLQ_TOPIC || 'eventzen.dlq',
};

export const EVENT_TYPES = {
  EVENT_PENDING_APPROVAL: 'EVENT_PENDING_APPROVAL',
  EVENT_STATUS_DECISION: 'EVENT_STATUS_DECISION',
  REGISTRATION_COMPLETED: 'REGISTRATION_COMPLETED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_ALLOCATION_FAILED: 'PAYMENT_ALLOCATION_FAILED',
};
