FROM node:20-alpine AS client-builder

WORKDIR /app/client
COPY client/package*.json ./
RUN npm ci
COPY client/ ./
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx/swagger/index.html /usr/share/nginx/html/swagger/index.html
COPY nginx/swagger/eventzen-aggregated.yaml /usr/share/nginx/html/openapi/eventzen-aggregated.yaml
COPY --from=client-builder /app/client/dist /usr/share/nginx/html
