#!/bin/sh
set -eu

if [ "${VAULT_ENABLED:-true}" != "true" ]; then
  exec "$@"
fi

if [ "$#" -eq 0 ]; then
  echo "vault-bootstrap: no startup command provided" >&2
  exit 1
fi

require_var() {
  var_name="$1"
  eval var_value="\${$var_name:-}"
  if [ -z "$var_value" ]; then
    echo "vault-bootstrap: required variable $var_name is missing" >&2
    exit 1
  fi
}

VAULT_ADDR="${VAULT_ADDR:-http://host.docker.internal:8200}"
VAULT_KV_MOUNT="${VAULT_KV_MOUNT:-secret}"
VAULT_ENV_FILE="${VAULT_ENV_FILE:-/tmp/vault-env.sh}"
VAULT_SHARED_CLIENT_TOKEN_FILE="${VAULT_SHARED_CLIENT_TOKEN_FILE:-/vault-runtime/client_token}"
VAULT_KV_PATH="${VAULT_KV_PATH:-}"

require_var VAULT_KV_PATH
require_var VAULT_SHARED_CLIENT_TOKEN_FILE

CURL_TLS_ARGS=""
if [ "${VAULT_SKIP_TLS_VERIFY:-false}" = "true" ]; then
  CURL_TLS_ARGS="-k"
fi

vault_curl() {
  method="$1"
  endpoint="$2"
  token="$3"
  body="${4:-}"
  url="${VAULT_ADDR%/}/v1/${endpoint#'/'}"

  if [ -n "$body" ]; then
    if [ -n "$token" ]; then
      curl -sS $CURL_TLS_ARGS -X "$method" \
        -H "X-Vault-Token: $token" \
        -H "Content-Type: application/json" \
        --data "$body" \
        "$url"
    else
      curl -sS $CURL_TLS_ARGS -X "$method" \
        -H "Content-Type: application/json" \
        --data "$body" \
        "$url"
    fi
  else
    if [ -n "$token" ]; then
      curl -sS $CURL_TLS_ARGS -X "$method" \
        -H "X-Vault-Token: $token" \
        "$url"
    else
      curl -sS $CURL_TLS_ARGS -X "$method" "$url"
    fi
  fi
}

if [ ! -f "$VAULT_SHARED_CLIENT_TOKEN_FILE" ]; then
  echo "vault-bootstrap: shared client token file not found at '$VAULT_SHARED_CLIENT_TOKEN_FILE'" >&2
  exit 1
fi

client_token="$(cat "$VAULT_SHARED_CLIENT_TOKEN_FILE")"
if [ -z "$client_token" ]; then
  echo "vault-bootstrap: shared client token file is empty at '$VAULT_SHARED_CLIENT_TOKEN_FILE'" >&2
  exit 1
fi

secret_response="$(vault_curl GET "${VAULT_KV_MOUNT#/}/data/${VAULT_KV_PATH#/}" "$client_token" "")"
secret_error="$(printf '%s' "$secret_response" | jq -r 'if .errors then .errors | join("; ") else empty end')"

if [ -n "$secret_error" ]; then
  echo "vault-bootstrap: failed reading secret path ${VAULT_KV_MOUNT}/data/${VAULT_KV_PATH}: $secret_error" >&2
  exit 1
fi

secret_count="$(printf '%s' "$secret_response" | jq -r '.data.data | length // 0')"
if [ "$secret_count" -eq 0 ]; then
  echo "vault-bootstrap: no key-values found at ${VAULT_KV_MOUNT}/data/${VAULT_KV_PATH}" >&2
  exit 1
fi

umask 077
{
  echo "# Generated by vault-bootstrap at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '%s' "$secret_response" | jq -r '.data.data | to_entries[] | "export \(.key)=\(.value|tostring|@sh)"'
} > "$VAULT_ENV_FILE"

# shellcheck disable=SC1090
. "$VAULT_ENV_FILE"

unset client_token

exec "$@"
